# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('amqp_2phase', '0001_create_events_table'),
    ]

    atomic = False
    operations = [
        migrations.RunSQL("""create index concurrently idx_amqp_events_pending on amqp_events(id) where status = 1;""",
                          reverse_sql="""drop index concurrently idx_amqp_events_pending;"""),
    ]
