# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 05:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amqp_2phase', '0002_create_event_index'),
    ]

    atomic = False
    operations = [
        migrations.RunSQL("""CREATE OR REPLACE FUNCTION notify_amqp_event() RETURNS TRIGGER AS $$
    BEGIN
        IF TG_OP = 'INSERT' THEN
            PERFORM pg_notify('amqp_events', (NEW.id)::varchar);
        END IF;

        RETURN NEW;
    END; $$ LANGUAGE plpgsql;""", reverse_sql="""DROP FUNCTION notify_amqp_event();"""),
    ]
