# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 05:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amqp_2phase', '0003_create_trigger_func'),
    ]

    atomic = False
    operations = [
        migrations.RunSQL(""" CREATE TRIGGER trg_notify_amqp_event
      after insert on amqp_events for each row
      EXECUTE PROCEDURE notify_amqp_event();""", reverse_sql="""DROP TRIGGER trg_notify_amqp_event ON amqp_events;"""),
    ]
