# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-03-14 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('amqp_2phase', '0004_create_trigger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amqpevent',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='amqpevent',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='amqpevent',
            name='send_date',
        ),
        migrations.RemoveField(
            model_name='amqpevent',
            name='status',
        ),
        migrations.RunSQL(
            """drop index concurrently idx_amqp_events_pending;""",
            reverse_sql="""create index concurrently idx_amqp_events_pending on amqp_events(id) where status = 1;""",
        ),
    ]
